name: concordance-nf
channels:
  - defaults
  - bioconda
#  - r
#  - biobuilds
  - conda-forge
dependencies:
  - bwa=0.7.17
  - sambamba=0.7.0
  - samtools=1.9
  - bamtools=2.5.1
  - picard=2.20.6
  - bcftools=1.9
  - fastqc=0.11.8
  - telseq=0.0.2
  - multiqc=1.7
#  - vcfkit=0.1.6
#  - csvtk=0.18.2
#  - r=3.6.0
#  - r-ggplot2=3.1.1
#  - r-readr=1.3.1
#  - r-tidyverse=1.2.1