name: nemascan
channels:
  - defaults
  - bioconda
  - r
  - biobuilds
  - conda-forge
dependencies:
  - bcftools=1.9
  - pandoc=2.12
  - plink=1.90b6.12
  - r=3.6.0 
  - r-lme4=1.1-23
  - r-devtools
  - r-boot=1.3-28
  - r-data.table=1.12.8
  - r-futile.logger=1.4.3
  - r-sommer=4.0.4
  - mscorefonts