name: r_packages
channels:
  - defaults
  - bioconda
  - r
  - biobuilds
  - conda-forge
dependencies:
  - pandoc=2.12
  - r=3.6.0
  - mscorefonts
  - r-data.table
  - r-DT
  - r-knitr
  - r-rmarkdown
  - r-plotly
  - r-cowplot
  - r-ggupset
  - r-patchwork
  - r-gsheet
  - r-BiocManager
  - r-igraph
  - r-ape
  - r-fuzzyjoin